import type { Phase1CaseDetail, Phase1TimelineEvent } from './types';

const DEFAULT_TIMELINE: Phase1TimelineEvent[] = [
  {
    id: 't1',
    icon: 'flag',
    title: 'Case reviewer changed to David Workeneh',
    who: 'David Workeneh',
    time: '10:19 AM',
    dateLabel: 'Feb 19, 2026',
  },
  {
    id: 't2',
    icon: 'lock',
    title: 'Case marked as restricted',
    who: 'System',
    time: '9:45 AM',
    dateLabel: 'Feb 19, 2026',
  },
  {
    id: 't3',
    icon: 'user',
    title: 'Case assigned to David Workeneh',
    who: 'Torq',
    time: '4:31 PM',
    dateLabel: 'Jan 1, 2026',
  },
];

const DEFAULT_SECURITY = {
  alertId: '—',
  incidentId: '—',
  source: '—',
  sourceProduct: '—',
  detectionName: '—',
  startTime: '—',
  endTime: '—',
  sourceSeverity: '—',
};

export const PHASE1_CASE_KEYS = ['4380', '4350', '4382', '4391', '4201'] as const;

export const PHASE1_CASE_DETAILS: Record<string, Phase1CaseDetail> = {
  '4380': {
    caseKey: '4380',
    displayId: '#4380',
    torqId: 'TQ-98033748',
    title: 'Ransomware alert',
    openedAt: 'Dec 09, 2024, 04:31 PM',
    editedAt: 'Feb 19, 2026, 10:19 AM',
    restricted: true,
    priority: 'high',
    slaElapsed: '-76w 1d',
    slaRemaining: '1d',
    pod: 'Threat defend pod',
    substateLabel: 'substate_3 / Cap…',
    capLabel: 'Triage flow',
    teamTag: 'content-team',
    statusTag: 'In progress',
    tags: ['Phishing', 'program', 'sensor'],
    extraTagCount: 2,
    attentionCount: 2,
    summary:
      'Automated ransomware alert from Wiz integration with correlated precursors and observables from triage.',
    summarySections: {
      what: 'Suspicious encryption-related activity detected on production workloads in us-east-1.',
      when: 'Dec 09, 2024 at 04:31 PM UTC; last activity observed Feb 19, 2026 at 10:12 AM.',
      impact: 'Two EC2 instances flagged; backup integrity checks pending. No confirmed data exfiltration.',
      keyIndicators: [
        'AWS Region: us-east-1',
        'Account ID: 123456789012',
        'Integration ID: wiz-prod-01',
        'Event ID: evt-9f2a11c8',
        'Event Source: wiz.security',
        'Event Timestamp: 2026-02-19T10:12:04Z',
      ],
    },
    summaryGeneratedAt: 'Generated a few seconds ago',
    description: '',
    timeline: DEFAULT_TIMELINE,
    tabCounts: { observables: 0, notes: 0, attachments: 0, linkedCases: 0, events: 1 },
    securityContext: {
      alertId: 'AL-882104',
      incidentId: 'INC-44021',
      source: 'Wiz',
      sourceProduct: 'CNAPP',
      detectionName: 'Ransomware precursor',
      startTime: '2024-12-09 16:31',
      endTime: '2026-02-19 10:12',
      sourceSeverity: 'High',
    },
    assigneeInitials: 'D',
    assigneeColor: '#2864FF',
  },
  '4350': {
    caseKey: '4350',
    displayId: '#4350',
    torqId: 'TQ-97412002',
    title: 'Phishing attempt',
    openedAt: 'May 18, 2026, 9:02 AM',
    editedAt: 'May 19, 2026, 11:20 AM',
    restricted: false,
    priority: 'medium',
    slaElapsed: '1d 4h',
    slaRemaining: '20h',
    pod: 'Acme Corp SOC',
    substateLabel: 'Investigation / Email…',
    capLabel: 'Phishing playbook',
    teamTag: 'soc-tier1',
    statusTag: 'In progress',
    tags: ['Phishing', 'email'],
    extraTagCount: 1,
    attentionCount: 1,
    summary: 'User-reported suspicious message; IOC enrichment and quarantine in progress.',
    summarySections: {
      what: 'Credential-harvesting link reported via internal phishing mailbox.',
      when: 'May 18, 2026 at 9:02 AM; last edit May 19, 2026 at 11:20 AM.',
      impact: 'Single mailbox affected; link blocked at proxy.',
      keyIndicators: [
        'Sender domain: support-it-helpdesk.net',
        'Message ID: msg-a91f002',
        'URL hash: sha256:9c2…',
      ],
    },
    summaryGeneratedAt: 'Generated 2 minutes ago',
    description: 'User reported a credential-harvesting link masquerading as IT support.',
    timeline: [
      {
        id: 'p1',
        icon: 'user',
        title: 'Analyst assigned to case',
        who: 'Sarah K.',
        time: '11:20 AM',
        dateLabel: 'May 19, 2026',
      },
      {
        id: 'p2',
        icon: 'flag',
        title: 'Priority set to medium',
        who: 'System',
        time: '9:15 AM',
        dateLabel: 'May 18, 2026',
      },
    ],
    tabCounts: { observables: 2, notes: 1, attachments: 0, linkedCases: 0, events: 3 },
    securityContext: { ...DEFAULT_SECURITY, source: 'Email', detectionName: 'Phishing' },
    assigneeInitials: 'S',
    assigneeColor: '#16A86C',
  },
  '4382': {
    caseKey: '4382',
    displayId: '#4382',
    torqId: 'TQ-98100219',
    title: 'Lateral movement',
    openedAt: 'May 19, 2026, 8:15 AM',
    editedAt: 'May 19, 2026, 10:48 AM',
    restricted: true,
    priority: 'high',
    slaElapsed: '2h 28m',
    slaRemaining: '1d 22h',
    pod: 'Threat defend pod',
    substateLabel: 'Containment / Host…',
    capLabel: 'Lateral movement',
    teamTag: 'threat-hunt',
    statusTag: 'In progress',
    tags: ['Lateral movement', 'C2'],
    extraTagCount: 0,
    attentionCount: 2,
    summary: 'Beaconing between internal hosts; investigation focuses on shared C2 indicators.',
    summarySections: {
      what: 'Repeated SMB and WinRM connections between two internal hosts.',
      when: 'May 19, 2026 starting 8:15 AM.',
      impact: 'Segmentation rules applied; hosts isolated pending forensics.',
      keyIndicators: ['Internal IP pair: 10.0.4.12 ↔ 10.0.4.88', 'C2 domain: update-cdn-secure.net'],
    },
    summaryGeneratedAt: 'Generated 8 minutes ago',
    description: '',
    timeline: DEFAULT_TIMELINE,
    tabCounts: { observables: 4, notes: 0, attachments: 1, linkedCases: 1, events: 5 },
    securityContext: { ...DEFAULT_SECURITY, detectionName: 'Lateral movement', sourceSeverity: 'High' },
    assigneeInitials: 'D',
    assigneeColor: '#2864FF',
  },
  '4391': {
    caseKey: '4391',
    displayId: '#4391',
    torqId: 'TQ-98155400',
    title: 'Ransomware precursor',
    openedAt: 'May 19, 2026, 6:30 AM',
    editedAt: 'May 19, 2026, 7:05 AM',
    restricted: true,
    priority: 'critical',
    slaElapsed: '45m',
    slaRemaining: '3h 15m',
    pod: 'Acme Corp SOC',
    substateLabel: 'P1 / Active…',
    capLabel: 'Ransomware response',
    teamTag: 'ir-lead',
    statusTag: 'Open',
    tags: ['Ransomware', 'P1'],
    extraTagCount: 1,
    attentionCount: 3,
    summary: 'P1 from automated triage: shadow-copy deletion and suspicious PowerShell.',
    summarySections: {
      what: 'Automated detection of ransomware precursor behaviors on endpoint fleet.',
      when: 'May 19, 2026 at 6:30 AM.',
      impact: 'Critical — executive escalation path engaged.',
      keyIndicators: ['Host: WIN-ENG-042', 'Command: vssadmin delete shadows /all'],
    },
    summaryGeneratedAt: 'Generated 1 minute ago',
    description: '',
    timeline: DEFAULT_TIMELINE,
    tabCounts: { observables: 1, notes: 0, attachments: 0, linkedCases: 0, events: 2 },
    securityContext: { ...DEFAULT_SECURITY, sourceSeverity: 'Critical' },
    assigneeInitials: 'D',
    assigneeColor: '#2864FF',
  },
  '4201': {
    caseKey: '4201',
    displayId: '#4201',
    torqId: 'TQ-96880012',
    title: 'Case bundle #4201',
    openedAt: 'May 12, 2026, 2:00 PM',
    editedAt: 'May 12, 2026, 4:18 PM',
    restricted: false,
    priority: 'low',
    slaElapsed: '—',
    slaRemaining: '—',
    pod: 'TechCorp Inc',
    substateLabel: 'Closed / Archive…',
    capLabel: 'Export bundle',
    teamTag: 'legal-hold',
    statusTag: 'Resolved',
    tags: ['Export'],
    extraTagCount: 0,
    attentionCount: 0,
    summary: 'Export bundle generated for legal hold and review.',
    summarySections: {
      what: 'Aggregated export of closed phishing cases for legal review.',
      when: 'May 12, 2026.',
      impact: 'No active threat — archival only.',
      keyIndicators: ['Bundle size: 2.4 GB', 'Cases included: 14'],
    },
    summaryGeneratedAt: 'Generated May 12, 2026',
    description: 'Contains observables and timeline for closed phishing cases.',
    timeline: [
      {
        id: 'b1',
        icon: 'workflow',
        title: 'Export bundle completed',
        who: 'System',
        time: '4:18 PM',
        dateLabel: 'May 12, 2026',
      },
    ],
    tabCounts: { observables: 0, notes: 0, attachments: 3, linkedCases: 14, events: 0 },
    securityContext: DEFAULT_SECURITY,
    assigneeInitials: 'L',
    assigneeColor: '#7C3AED',
  },
};

export function getPhase1CaseDetail(caseKey: string): Phase1CaseDetail {
  return (
    PHASE1_CASE_DETAILS[caseKey] ?? {
      caseKey,
      displayId: `#${caseKey}`,
      torqId: `TQ-${caseKey.padStart(8, '0')}`,
      title: `Case ${caseKey}`,
      openedAt: '—',
      editedAt: '—',
      restricted: false,
      priority: 'low',
      slaElapsed: '—',
      slaRemaining: '—',
      pod: 'Acme Corp SOC',
      substateLabel: 'Open / New…',
      capLabel: 'Default flow',
      teamTag: 'soc-team',
      statusTag: 'Open',
      tags: [],
      extraTagCount: 0,
      attentionCount: 0,
      summary: 'Case details will load here when connected to the cases service.',
      summarySections: {
        what: '—',
        when: '—',
        impact: '—',
        keyIndicators: [],
      },
      summaryGeneratedAt: 'Not yet generated',
      description: '',
      timeline: DEFAULT_TIMELINE,
      tabCounts: { observables: 0, notes: 0, attachments: 0, linkedCases: 0, events: 0 },
      securityContext: DEFAULT_SECURITY,
      assigneeInitials: 'D',
      assigneeColor: '#2864FF',
    }
  );
}
