import type { Phase1Notification, Phase1WorkflowGroup } from './types';
import type { AiCreditNotifVariant } from '@/lib/workspaceAiCredits';
import {
  getAiCreditNotificationCopy,
  getAiCreditsSnapshotForNotif,
  getWorkspaceAiCredits,
} from '@/lib/workspaceAiCredits';
import { workspaceAccentColor, workspaceLabel } from './phase1InboxWorkspace';

function agoMs(ms: number): string {
  return new Date(Date.now() - ms).toISOString();
}

const m = (n: number) => n * 60 * 1000;
const h = (n: number) => n * 60 * 60 * 1000;
const d = (n: number) => n * 24 * 60 * 60 * 1000;

const TORQ_DEV = 'torq-dev';
const TORQ_STAGING = 'torq-staging';
const TORQ_PROD = 'torq-prod';
const ACME_CORP = 'acme-corp';
const TORQ_DEV_LABEL = workspaceLabel(TORQ_DEV);
const TORQ_STAGING_LABEL = workspaceLabel(TORQ_STAGING);
const TORQ_PROD_LABEL = workspaceLabel(TORQ_PROD);
const TORQ_DEV_BLUE = workspaceAccentColor(TORQ_DEV);
const TORQ_STAGING_PURPLE = workspaceAccentColor(TORQ_STAGING);
const TORQ_PROD_RED = workspaceAccentColor(TORQ_PROD);

const TORQ_AVATAR_BG = '#090A0B';
const WORKFLOW_AVATAR_BG = '#FDD711';
const CASE_AVATAR_BG = '#2864FF';
const FAIL_BADGE = '#DC2626';
const WARN_BADGE = '#D97706';
const NEUTRAL_BADGE = '#9CA3AF';
const SUCCESS_BADGE = '#16A34A';

const TOMER_AVATAR = { initials: 'T', color: TORQ_DEV_BLUE };
const TZOFIA_AVATAR = { initials: 'T', color: TORQ_DEV_BLUE };

function aiCreditNotif(
  id: string,
  workspaceId: string,
  variant: AiCreditNotifVariant,
  overrides: Partial<Phase1Notification>,
): Phase1Notification {
  const credits = getWorkspaceAiCredits(workspaceId);
  const copy = getAiCreditNotificationCopy(credits, variant);
  const badgeBg =
    copy.severity === 'critical' ? FAIL_BADGE : copy.severity === 'high' ? WARN_BADGE : NEUTRAL_BADGE;
  return {
    id,
    zone: 'feed',
    severity: copy.severity,
    title: copy.title,
    body: copy.body,
    workspaceId,
    workspace: workspaceLabel(workspaceId),
    avatarBg: TORQ_AVATAR_BG,
    badgeBg,
    avatarIcon: 'ai',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
    aiCreditsSnapshot: getAiCreditsSnapshotForNotif(credits, variant),
    occurredAt: agoMs(m(11)),
    ...overrides,
  };
}

/** Phase 1 inbox seed — grouped by torq-dev / torq-staging / torq-prod for 50/25/25 mix */
export const PHASE1_NOTIFICATIONS: Phase1Notification[] = [
  // Workflow
  {
    id: 'n1',
    zone: 'pinned',
    severity: 'critical',
    title: 'Workflow execution failed — Malware triage endpoint',
    body: 'Step "Enrich IP" failed · Step 4 of 9',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(m(3)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Malware triage endpoint' },
  },
  {
    id: 'n2',
    zone: 'feed',
    severity: 'high',
    title: 'Workflow share failed — Phishing response v2',
    body: 'Step "Send alert" failed · Step 2 of 6',
    workspaceId: TORQ_STAGING,
    workspace: workspaceLabel(TORQ_STAGING),
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(28)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Phishing response v2' },
  },
  {
    id: 'n3',
    zone: 'feed',
    severity: 'high',
    title: 'Tomer Braunstain requested to publish Phishing auto-triage v3',
    body: 'Awaiting your review · submitted 4 hr ago',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(m(35)),
    avatarIcon: 'publish',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Phishing auto-triage v3' },
    personAvatar: TOMER_AVATAR,
  },
  // AI Credits & Licensing (aligned with Usage tab + preview card)
  aiCreditNotif('n4', TORQ_DEV, 'exceeded', {
    zone: 'pinned',
    occurredAt: agoMs(m(11)),
  }),
  aiCreditNotif('n6', TORQ_DEV, 'summary', {
    occurredAt: agoMs(h(32)),
  }),
  // Case Management
  {
    id: 'n7',
    zone: 'feed',
    severity: 'high',
    title: 'Tomer Braunstain mentioned you in Case #4380 — Ransomware alert',
    body: '"Can you review this IOC?"',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(h(1)),
    avatarIcon: 'mention',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4380' },
    personAvatar: TOMER_AVATAR,
  },
  // Case Exports
  {
    id: 'n8',
    zone: 'feed',
    severity: 'high',
    title: 'Case export failed — file too large',
    body: 'Requested Jul 23, 2025 · Try again with less data',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(3)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4350' },
  },
  {
    id: 'n9',
    zone: 'feed',
    severity: 'high',
    title: 'Case export failed — file size limit reached',
    body: 'Export exceeds 500 MB limit · Reduce case scope',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(d(3)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4350' },
  },
  {
    id: 'n10',
    zone: 'feed',
    severity: 'low',
    title: 'Case export failed — please try again',
    body: 'Requested Jul 22, 2025 · Something went wrong on our end',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(h(26)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4350' },
  },
  // Sharing & Collaboration
  {
    id: 'n11',
    zone: 'feed',
    severity: 'high',
    title: 'Tzofia Bar shared CrowdStrike connector with you',
    body: 'From workspace: torq-internal · Integration',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(h(27)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
    personAvatar: TZOFIA_AVATAR,
  },
  {
    id: 'n12',
    zone: 'feed',
    severity: 'low',
    title: 'CrowdStrike connector sharing request was declined',
    body: 'Declined by torq-internal · Contact tomer@torq.io if this was a mistake. The workspace owner can re-invite you from Organization settings once access is approved.',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(d(9)),
    avatarIcon: 'connector',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n13',
    zone: 'feed',
    severity: 'low',
    title: 'SentinelOne connector was approved and added to your workspace',
    body: 'Shared by torq-internal · Edit sharing settings anytime',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: SUCCESS_BADGE,
    occurredAt: agoMs(d(12)),
    avatarIcon: 'connector',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n14',
    zone: 'feed',
    severity: 'high',
    title: 'Tim Adams mentioned you in Case #4412 — Suspicious login',
    body: '"Please confirm the user offboarding timeline and whether we should revoke active sessions before the Friday change window."',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(m(90)),
    avatarIcon: 'mention',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4412' },
    personAvatar: { initials: 'T', color: TORQ_DEV_BLUE },
  },
  // torq-staging
  {
    id: 'n16',
    zone: 'pinned',
    severity: 'critical',
    title: 'Workflow execution failed — Staging EDR ingest',
    body: 'Step "Normalize events" failed · Step 2 of 5',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(m(18)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Staging EDR ingest' },
  },
  {
    id: 'n17',
    zone: 'feed',
    severity: 'high',
    title: 'Sarah Chen mentioned you in Case #5201 — Lateral movement',
    body: '"Can you validate the staging IOC list?"',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(m(55)),
    avatarIcon: 'mention',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '5201' },
    personAvatar: { initials: 'S', color: TORQ_STAGING_PURPLE },
  },
  aiCreditNotif('n18', TORQ_STAGING, 'warning', {
    occurredAt: agoMs(h(2)),
  }),
  {
    id: 'n19',
    zone: 'feed',
    severity: 'low',
    title: 'Sam Lee shared SentinelOne playbook with you',
    body: 'Genesis-Dev-58 · Review before publish',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(h(26)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
    personAvatar: { initials: 'S', color: TORQ_STAGING_PURPLE },
  },
  {
    id: 'n20',
    zone: 'feed',
    severity: 'high',
    title: 'Case export failed — Genesis-Dev-58 export quota',
    body: 'Reduce export scope or request quota increase',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(d(3)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '5190' },
  },
  // torq-prod
  aiCreditNotif('n21', TORQ_PROD, 'exceeded', {
    zone: 'pinned',
    occurredAt: agoMs(m(7)),
  }),
  {
    id: 'n22',
    zone: 'feed',
    severity: 'high',
    title: 'Paul Miller mentioned you in Case #8802 — Data exfiltration',
    body: '"Need prod approval before isolation"',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(m(42)),
    avatarIcon: 'mention',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '8802' },
    personAvatar: { initials: 'P', color: TORQ_PROD_RED },
  },
  {
    id: 'n23',
    zone: 'feed',
    severity: 'high',
    title: 'Workflow execution failed — Prod ransomware response',
    body: 'Step "Isolate host" failed · Step 6 of 8',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(4)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Prod ransomware response' },
  },
  {
    id: 'n24',
    zone: 'feed',
    severity: 'low',
    title: 'Priya Patel requested to publish Prod phishing v4',
    body: 'Awaiting your review · submitted yesterday',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(h(30)),
    avatarIcon: 'publish',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Prod phishing v4' },
    personAvatar: { initials: 'P', color: TORQ_PROD_RED },
  },
  {
    id: 'n25',
    zone: 'feed',
    severity: 'low',
    title: 'Case export ready for download',
    body: 'Case #8700 · Expires in 48 hours',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: SUCCESS_BADGE,
    occurredAt: agoMs(d(6)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '8700' },
  },
  // Today — sharing & collaboration templates
  {
    id: 'n26',
    zone: 'feed',
    severity: 'low',
    title: 'Auto-Remediate Disk Space was shared with torq-dev',
    body: 'Shared by Alex Rivera from Security-Ops · Review workflow permissions and confirm whether production triggers should inherit the new integration defaults.',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(m(4)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Auto-Remediate Disk Space' },
    personAvatar: { initials: 'A', color: TORQ_DEV_BLUE },
  },
  {
    id: 'n27',
    zone: 'feed',
    severity: 'low',
    title: 'Jira Cloud integration was shared with Genesis-Dev-58',
    body: 'Shared by Jordan Smith from External-Partner · Review integration scopes, webhook URLs, and whether read-only access is sufficient for the audit window.',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(m(6)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
    personAvatar: { initials: 'J', color: TORQ_STAGING_PURPLE },
  },
  {
    id: 'n28',
    zone: 'feed',
    severity: 'low',
    title: 'Parse JSON Log step was shared with Pinnacle-Prod',
    body: 'Shared by System from Global-Library · Review step',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(m(9)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n29',
    zone: 'feed',
    severity: 'low',
    title: 'AWS Production Workflow was added to torq-dev',
    body: 'Shared by torq-dev · Edit sharing settings',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: SUCCESS_BADGE,
    occurredAt: agoMs(m(12)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'AWS Production Workflow' },
  },
  {
    id: 'n30',
    zone: 'feed',
    severity: 'high',
    title: 'CrowdStrike connector sharing request was declined by Genesis-Dev-58',
    body: 'Contact admin@torq.io if you believe this was a mistake',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(m(16)),
    avatarIcon: 'connector',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n31',
    zone: 'feed',
    severity: 'low',
    title: 'Organization Manager role assigned in Acme Corp',
    body: 'Activate your account to start managing the organization',
    workspaceId: ACME_CORP,
    workspace: 'Acme Corp',
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(m(20)),
    avatarIcon: 'organization',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n32',
    zone: 'feed',
    severity: 'low',
    title: 'Alex Rivera invited you to join Acme Corp',
    body: 'Contact support@torq.io if you believe this was a mistake',
    workspaceId: ACME_CORP,
    workspace: 'Acme Corp',
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(m(24)),
    avatarIcon: 'invite',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
    personAvatar: { initials: 'A', color: TORQ_DEV_BLUE },
  },
  {
    id: 'n33',
    zone: 'feed',
    severity: 'low',
    title: 'Security Secret was added to Pinnacle-Prod',
    body: 'Shared by Pinnacle-Prod · Edit sharing settings',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: SUCCESS_BADGE,
    occurredAt: agoMs(m(32)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  // This week — mixed types & workspaces (yesterday / 2–4 days ago)
  {
    id: 'n34',
    zone: 'feed',
    severity: 'high',
    title: 'Case export failed — audit bundle timeout',
    body: 'Requested yesterday · Retry with fewer observables',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(25)),
    avatarIcon: 'export',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '4391' },
  },
  {
    id: 'n35',
    zone: 'feed',
    severity: 'critical',
    title: 'Workflow execution failed — Off-hours DLP scan',
    body: 'Step "Classify files" failed · Step 3 of 7',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(31)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'Off-hours DLP scan' },
  },
  aiCreditNotif('n36', TORQ_PROD, 'warning', {
    occurredAt: agoMs(h(29)),
  }),
  {
    id: 'n37',
    zone: 'feed',
    severity: 'low',
    title: 'Slack connector sharing request was declined by torq-internal',
    body: 'Contact integrations@torq.io if you believe this was a mistake',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(h(33)),
    avatarIcon: 'connector',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n38',
    zone: 'feed',
    severity: 'high',
    title: 'Jordan Smith mentioned you in Case #5210 — Credential leak',
    body: '"Can you confirm rotation completed?"',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: CASE_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(h(28)),
    avatarIcon: 'mention',
    contentScreen: 'cases',
    target: { type: 'case', caseKey: '5210' },
    personAvatar: { initials: 'J', color: TORQ_STAGING_PURPLE },
  },
  {
    id: 'n39',
    zone: 'feed',
    severity: 'high',
    title: 'Workflow execution failed — VPN posture check',
    body: 'Step "Validate certificate" failed · Step 1 of 4',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: FAIL_BADGE,
    occurredAt: agoMs(h(34)),
    avatarIcon: 'workflow',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'VPN posture check' },
  },
  {
    id: 'n40',
    zone: 'feed',
    severity: 'high',
    title: 'Maya Cohen requested to publish IOC enrichment v2',
    body: 'Awaiting your review · submitted yesterday',
    workspaceId: TORQ_DEV,
    workspace: TORQ_DEV_LABEL,
    avatarBg: WORKFLOW_AVATAR_BG,
    badgeBg: WARN_BADGE,
    occurredAt: agoMs(h(26)),
    avatarIcon: 'publish',
    contentScreen: 'workflows',
    target: { type: 'workflow', workflowName: 'IOC enrichment v2' },
    personAvatar: { initials: 'M', color: TORQ_DEV_BLUE },
  },
  {
    id: 'n41',
    zone: 'feed',
    severity: 'low',
    title: 'PagerDuty connector was approved and added to your workspace',
    body: 'Shared by Genesis-Dev-58 · Edit sharing settings anytime',
    workspaceId: TORQ_STAGING,
    workspace: TORQ_STAGING_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: SUCCESS_BADGE,
    occurredAt: agoMs(d(2)),
    avatarIcon: 'connector',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  {
    id: 'n42',
    zone: 'feed',
    severity: 'low',
    title: 'ServiceNow playbook was shared with Pinnacle-Prod',
    body: 'Shared by Ops-Automation · Review workflow',
    workspaceId: TORQ_PROD,
    workspace: TORQ_PROD_LABEL,
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(d(3)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
  // Outside the 3-workspace mix (fill only if pools run short)
  {
    id: 'n15',
    zone: 'feed',
    severity: 'low',
    title: 'Alex Kim shared Phishing Response Playbook with you',
    body: 'From workspace: acme-corp · Review before enabling. The connector requests read access to cases, workflows, and audit logs for the next 30 days.',
    workspaceId: ACME_CORP,
    workspace: workspaceLabel(ACME_CORP),
    avatarBg: TORQ_AVATAR_BG,
    badgeBg: NEUTRAL_BADGE,
    occurredAt: agoMs(d(5)),
    avatarIcon: 'share',
    contentScreen: 'workflows',
    target: { type: 'workflows' },
  },
];

export const PHASE1_INITIAL_STATES: Record<string, 'unseen' | 'seen' | 'read'> = {
  n1: 'unseen',
  n2: 'unseen',
  n3: 'unseen',
  n4: 'unseen',
  n6: 'seen',
  n7: 'unseen',
  n8: 'unseen',
  n9: 'unseen',
  n10: 'read',
  n11: 'seen',
  n12: 'read',
  n13: 'read',
  n14: 'unseen',
  n15: 'read',
  n16: 'unseen',
  n17: 'unseen',
  n18: 'unseen',
  n19: 'seen',
  n20: 'unseen',
  n21: 'unseen',
  n22: 'unseen',
  n23: 'unseen',
  n24: 'read',
  n25: 'read',
  n26: 'unseen',
  n27: 'unseen',
  n28: 'unseen',
  n29: 'unseen',
  n30: 'unseen',
  n31: 'unseen',
  n32: 'unseen',
  n33: 'seen',
  n34: 'unseen',
  n35: 'unseen',
  n36: 'unseen',
  n37: 'read',
  n38: 'unseen',
  n39: 'unseen',
  n40: 'seen',
  n41: 'read',
  n42: 'unseen',
};

export type Phase1Workspace = { id: string; name: string; isCurrent?: boolean };

export const PHASE1_WORKSPACES: Phase1Workspace[] = [
  { id: 'acme-corp', name: 'Acme Corp', isCurrent: true },
  { id: 'techcorp', name: 'TechCorp Inc' },
  { id: 'financegroup', name: 'FinanceGroup' },
  { id: 'cybershield', name: 'CyberShield Ltd' },
];

export const PHASE1_WORKFLOW_GROUPS: Phase1WorkflowGroup[] = [
  {
    id: 'r0ma',
    name: 'r0ma',
    expanded: true,
    workflows: [
      {
        id: 'wf-r1',
        name: 'Roma-interact',
        state: 'active',
        statusBar: 'success',
        statusIcon: 'globe',
        triggerType: 'webhook',
        tags: [
          '999999999',
          'Data transformation Us...',
          'agentic-builder',
          'slack',
          'webhook',
          'case',
          'export',
          'triage',
          'email',
          'dev',
          'v2',
          'auto',
          'roma',
          'test',
        ],
        triggeredBy: {
          label: 'Raveed Laeb',
          timestamp: 'May 24 2026, 2:33 PM',
          initials: 'R',
          avatarColor: '#1A73E8',
          avatarUrl: 'https://i.pravatar.cc/96?img=12',
        },
        lastModifiedBy: {
          name: 'Roma Kunicher',
          initials: 'R',
          avatarColor: '#9334E6',
          avatarUrl: 'https://i.pravatar.cc/96?img=32',
          timestamp: 'May 24 2026, 2:33 PM',
        },
        shared: true,
        executions7d: 128,
      },
      {
        id: 'wf-r2',
        name: 'Roma sandbox',
        state: 'active',
        statusBar: 'warning',
        statusIcon: 'progress',
        triggerType: 'schedule',
        tags: ['sandbox', 'test'],
        triggeredBy: { label: 'Scheduled event', timestamp: 'May 23 2026, 5:00 PM' },
        lastModifiedBy: {
          name: 'Alon Gat',
          initials: 'A',
          avatarColor: '#E37400',
          timestamp: 'May 24 2026, 2:33 PM',
        },
        shared: false,
        executions7d: 47,
      },
      {
        id: 'wf-r3',
        name: "Ivans' workflow 21",
        state: 'active',
        statusBar: 'success',
        statusIcon: 'globe-linked',
        triggerType: 'webhook',
        tags: ['dev'],
        triggeredBy: { label: 'crowdstrike-falcon', timestamp: 'May 22 2026, 11:15 AM' },
        lastModifiedBy: {
          name: 'Ivan Hromau',
          initials: 'I',
          avatarColor: '#0D652D',
          avatarUrl: 'https://i.pravatar.cc/96?img=33',
          timestamp: 'Nov 4 2026, 2:06 PM',
        },
        shared: false,
        executions7d: 12,
      },
      {
        id: 'wf-r4',
        name: 'roma dev',
        state: 'inactive',
        statusBar: 'success',
        statusIcon: 'globe',
        triggerType: 'manual',
        tags: ['dev'],
        triggeredBy: { label: 'Manual trigger' },
        lastModifiedBy: {
          name: 'Tomer Braunstain',
          initials: 'T',
          avatarColor: '#1A73E8',
          timestamp: 'May 20 2026, 9:41 AM',
        },
        shared: true,
        executions7d: 3,
      },
    ],
  },
  { id: 'bh-new', name: '_BH_new', itemCount: 1, workflows: [] },
  { id: 'wip', name: '# Work in Progress', itemCount: 5, workflows: [] },
  { id: 'aa', name: 'AA', itemCount: 13, workflows: [] },
];
